// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qinoxhpvnunuemqvpdla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpbm94aHB2bnVudWVtcXZwZGxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3OTk2NTYsImV4cCI6MjA1NzM3NTY1Nn0.aVKnjqQafmdBUt_9VIoNKEZwo9pFrbQCTpI3jPzWmBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);